CREATE TABLE BOOK (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    borrowed BOOLEAN NOT NULL
);

CREATE TABLE STUDENT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);

CREATE TABLE FINE (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    rate_per_day DECIMAL(5, 2) NOT NULL
);
